import type { Metadata } from "next";
import "./globals.css";
import { jakarta } from "@/fonts";



export const metadata: Metadata = {
  title: "My Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jakarta.className}>{children}</body>
    </html>
  );
}
